// Generated by CoffeeScript 1.3.3
var sStory;

sStory = function(sections) {
  var container;
  container = d3.select("#container");
  return container.selectAll('.section').data(sections).enter().append("div").attr("class", "section").html(function(d, i) {
    var html;
    switch (d.type) {
      case "image":
        console.log("image");
        html = ich.image(d, true);
        break;
      case "image2":
        console.log("image2");
        html = ich.image2(d, true);
        break;
      case "image3":
        console.log("image3");
        html = ich.image3(d, true);
        break;
      case "vimeo":
        console.log("vimeo");
        break;
      case "soundcloud":
        console.log("soundcloud");
        break;
      case "map":
        console.log("map");
        break;
      case "timeline":
        console.log("timeline");
    }
    return html;
  });
};
