// Generated by CoffeeScript 1.6.2
var sStory;

sStory = (function() {
  function sStory(story_list) {
    var typeIsArray;

    this.story_list = story_list;
    typeIsArray = Array.isArray || function(value) {
      return {}.toString.call(value) === '[object Array]';
    };
    if (this.story_list === void 0) {
      throw "No story_list defined";
    }
    if (!typeIsArray(this.story_list)) {
      throw "The story_list is not an array";
    }
  }

  sStory.prototype.render = function() {
    /*
    $targetContainer = $("#content")
    $targetContainer.html(JSON.stringify(@story_list))
    */

    var sections, targetContainer, that;

    targetContainer = d3.select("#content");
    sections = targetContainer.selectAll("section").data(this.story_list).enter().append("section").attr('class', function(d) {
      return d.type;
    }).text("boop");
    targetContainer.selectAll('.photoBigText').style("background-image", function(d) {
      return "url(" + d.photoUrl + ")";
    }).append("h2").text(function(d) {
      return d.title;
    });
    this.handleWindowResize();
    that = this;
    $(window).on('resize', function() {
      return that.handleWindowResize();
    });
    this.makeNavSectionList();
    return this.story_list;
  };

  sStory.prototype.makeNavSectionList = function() {
    var $navlist;

    $navlist = $("#nav-section-list");
    $navlist.html("");
    return _.each(this.story_list, function(section, i) {
      var $link, $listItem;

      $link = $("<a></a>").attr("href", "#" + i).html(i + 1);
      $listItem = $("<li></li>").html($link);
      return $navlist.append($listItem);
    });
  };

  sStory.prototype.verticalCenterElement = function(el, parEl) {
    var elHeight, pageHeight;

    elHeight = el.innerHeight() / 2;
    pageHeight = parEl.innerHeight() / 2;
    return $(el).css({
      paddingTop: pageHeight - elHeight
    });
  };

  sStory.prototype.verticalCenterPhotoTitles = function() {
    var that;

    that = this;
    return $(".photoBigText h2").each(function() {
      return that.verticalCenterElement($(this), $(this).parent());
    });
  };

  sStory.prototype.handleWindowResize = function() {
    var windowHeight;

    this.verticalCenterPhotoTitles();
    windowHeight = $(window).height();
    $(".photoBigText .photo-background").css({
      minHeight: windowHeight
    });
    return $(".photoCaption .photo-background").css({
      minHeight: windowHeight
    });
  };

  return sStory;

})();
