// Generated by CoffeeScript 1.6.2
var sStory;

sStory = (function() {
  var handleScroll;

  function sStory(story_list, options) {
    var typeIsArray;

    this.story_list = story_list;
    this.options = options;
    typeIsArray = Array.isArray || function(value) {
      return {}.toString.call(value) === '[object Array]';
    };
    if (this.story_list === void 0) {
      throw "No story_list defined";
    }
    if (!typeIsArray(this.story_list)) {
      throw "The story_list is not an array";
    }
    this.options = {
      targetID: '#content'
    };
  }

  sStory.prototype.render = function() {
    var codeGist, codeTributary, locationSinglePlace, locationTimeline, photoBigText, photoCaption, photoMulti, sections, soundSoundcloud, targetContainer, targetID, text, that, timelineStorify, timelineVerite, videoVimeo, videoYoutube;

    targetID = this.options.targetID;
    targetContainer = d3.select(targetID);
    sections = targetContainer.selectAll("section").data(this.story_list).enter().append("section").attr('class', function(d) {
      return d.type;
    }).attr('data-title', function(d) {
      return d.title;
    }).attr('id', function(d, i) {
      return 'section' + (i + 1);
    });
    photoBigText = targetContainer.selectAll('.photoBigText').attr('class', 'photoBigText photo').style("background-image", function(d) {
      return "url(" + d.photoUrl + ")";
    }).append("h2").text(function(d) {
      return d.title;
    });
    photoCaption = targetContainer.selectAll('.photoCaption').attr('class', 'photoCaption photo').style("background-image", function(d) {
      return "url(" + d.photoUrl + ")";
    });
    photoCaption.append("h2").text(function(d) {
      return d.title;
    });
    photoCaption.append("aside").attr("class", "caption").html(function(d) {
      return d.caption;
    });
    photoMulti = targetContainer.selectAll('.photoMulti').attr('data-layout', '12312');
    photoMulti.selectAll('img').data(photoMulti[0][0].__data__.photoUrlArray).enter().append('img').attr('src', function(d) {
      return d;
    });
    videoYoutube = targetContainer.selectAll(".videoYoutube").append("div").attr("class", "video-container").html(function(d) {
      return d.embedCode;
    });
    videoVimeo = targetContainer.selectAll(".videoVimeo").append("div").attr("class", "video-container").html(function(d) {
      return d.embedCode;
    });
    soundSoundcloud = targetContainer.selectAll(".soundSoundcloud").html(function(d) {
      return d.embedCode;
    });
    codeGist = targetContainer.selectAll(".codeGist").html(function(d) {
      var gistHtml, id;

      gistHtml = "";
      id = d.url.split('/')[4];
      $.get("https://api.github.com/gists/" + id, function(d) {
        return _.each(d.files, function(d) {
          gistHtml += "<h3>" + d.filename + "</h3>";
          return gistHtml += "<div class='content'>" + d.content + "</div>";
        });
      });
      return gistHtml;
    });
    codeTributary = targetContainer.selectAll(".codeTributary").append("iframe").attr("src", function(d) {
      return d.url;
    });
    text = targetContainer.selectAll(".text").html(function(d) {
      return d.html;
    });
    timelineVerite = targetContainer.selectAll(".timelineVerite").append("div").attr("class", "timeline-container").html(function(d) {
      return d.embedCode;
    });
    timelineStorify = targetContainer.selectAll('.timelineStorify').append("div").attr("class", "timeline-container").html(function(d) {
      return d.embedCode;
    });
    locationSinglePlace = targetContainer.selectAll(".locationSinglePlace").append("div").attr("class", "map").attr("data-address", function(d) {
      return d.address;
    }).attr("data-caption", function(d) {
      return d.caption;
    }).attr("data-zoom", function(d) {
      return d.zoom;
    }).style("height", this.windowHeight);
    locationTimeline = targetContainer.selectAll('locationTimeline').append("div").attr("class", "map multi-location");
    that = this;
    $(window).on('resize', function() {
      return that.handleWindowResize();
    });
    this.renderMaps();
    this.renderPhotosets();
    this.makeNavSectionList();
    this.handleWindowResize();
    this.windowHeight = $(window).height();
    $('.photo').css('height', this.windowHeight);
    return this.story_list;
  };

  sStory.prototype.makeNavSectionList = function() {
    var $header, $navlist;

    $navlist = $("#navigation");
    $navlist.html("");
    _.each(this.story_list, function(section, i) {
      var $link, $listItem, content, listClass;

      listClass = "";
      content = i + 1;
      if (section.title !== void 0) {
        content = section.title;
        listClass = 'titled';
      }
      $link = $("<a></a>").attr("href", "#section" + (i + 1)).html(content);
      $listItem = $("<li class='" + listClass + "' id='" + i + "'></li>").attr('data-background-image', function() {
        return section.photoUrl;
      }).css('background-image', function() {
        if (section.photoUrl !== void 0) {
          return "url(" + section.photoUrl + ")";
        }
      }).append($('<div class="outerContainer"> </div>')).append($('<div class="innerContainer"> </div>')).append($('<div class="element"> </div>')).html($link);
      return $navlist.append($listItem);
    });
    $navlist.find('li:not(.titled)').fitText(0.1);
    $header = $('#header-content');
    $('#header-front').click(function() {
      $header.removeClass('show-front');
      return $header.addClass('show-bottom');
    });
    $('#navigation').click(function(event) {
      var $evtTgt, $target, targetID;

      $evtTgt = $(event.target);
      if ($evtTgt.prop('tagName') === 'A') {
        targetID = $evtTgt.prop('hash');
        $target = $(targetID);
        $('html,body').animate({
          scrollTop: $target.offset().top
        }, 1000);
        return event.preventDefault();
      } else {
        $header.removeClass('show-bottom');
        return $header.addClass('show-front');
      }
    });
    return $(window).on('scroll', function() {
      var $sections;

      $sections = $('section');
      return handleScroll($sections);
    });
  };

  sStory.prototype.handleWindowResize = function() {
    var that, windowHeight;

    this.verticalCenterPhotoTitles();
    that = this;
    $('#navigation li.titled a').each(function(i, el) {
      return that.verticalCenterElement($(el), $(el).parent());
    });
    windowHeight = $(window).height();
    $(".photoBigText .photo-background").css({
      minHeight: windowHeight
    });
    return $(".photoCaption .photo-background").css({
      minHeight: windowHeight
    });
  };

  handleScroll = function(sections) {
    var $header, bodyHeight, position, scrollTop;

    $header = $('#header-content');
    scrollTop = $(window).scrollTop();
    bodyHeight = $('body').height();
    if (scrollTop > 500) {
      position = ((scrollTop + $(window).height()) / bodyHeight) * 100;
    } else {
      position = (scrollTop / bodyHeight) * 100;
    }
    if (position > 100) {
      position = 100;
    }
    $('#progress').css('width', position + '%');
    if (scrollTop >= 110) {
      $header.addClass('small');
      return $header.css('margin-top', '1em');
    } else {
      $header.removeClass('small');
      return $header.css('margin-top', 0);
    }
  };

  sStory.prototype.verticalCenterElement = function(el, parEl) {
    var elHeight, pageHeight;

    elHeight = el.innerHeight() / 2;
    pageHeight = parEl.innerHeight() / 2;
    return $(el).css({
      paddingTop: pageHeight - elHeight
    });
  };

  sStory.prototype.verticalCenterPhotoTitles = function() {
    var that;

    that = this;
    $(".photoBigText h2").each(function() {
      return that.verticalCenterElement($(this), $(this).parent());
    });
    return $(".photoCaption h2").each(function() {
      return that.verticalCenterElement($(this), $(this).parent());
    });
  };

  sStory.prototype.renderPhotosets = function() {
    var multiPhotoPadding;

    multiPhotoPadding = $('.photoMulti').first().css('padding');
    return $('.photoMulti').photosetGrid({
      gutter: multiPhotoPadding + 'px'
    });
  };

  sStory.prototype.renderMaps = function() {
    var that;

    that = this;
    return $(".map").each(function() {
      var address, caption, geoCode, latLon, mapId, zoom;

      mapId = _.uniqueId("map_");
      $(this).attr("id", mapId);
      address = $(this).attr("data-address");
      caption = $(this).attr("data-caption");
      zoom = $(this).attr("data-zoom");
      if (zoom === void 0 || zoom === "") {
        zoom = 14;
      }
      latLon = [];
      geoCode = that.geocodeLocationRequest(address);
      return geoCode.done(function(result) {
        var circle, layer, map;

        result = result[0];
        latLon = [result.lat, result.lon];
        map = L.map(mapId, {
          scrollWheelZoom: false
        }).setView(latLon, zoom);
        layer = new L.StamenTileLayer("toner-lite");
        map.addLayer(layer);
        return circle = L.circle(latLon, 120, {
          color: 'red',
          fillColor: 'red',
          fillOpacity: 0.8,
          closeOnClick: false
        }).bindPopup(caption, {
          maxWidth: 600,
          maxHeight: 600,
          closeButton: false
        }).addTo(map).openPopup();
      });
    });
  };

  sStory.prototype.geocodeLocationRequest = function(location) {
    var addr, baseUrl, url;

    baseUrl = "http://open.mapquestapi.com/nominatim/v1/search.php?format=json";
    addr = "&q=" + location;
    url = encodeURI(baseUrl + addr + "&addressdetails=1&limit=1");
    return $.ajax({
      url: url,
      type: "GET",
      dataType: "json",
      cache: true
    });
  };

  return sStory;

})();
